GET http://localhost:4000/ping


###

POST http://localhost:4000/auth/registrar
content-type: application/json

{
    "nome":  "Wesley Machado",
    "email":"wesley.machado@empresa.com.br",
    "senha":"#3c5x9cfg",
    "telefone":"(34) 98443-1247",
    "barbeiro": false
}


###
POST http://localhost:4000/auth/login
content-type: application/json

{
    "email":"wesley.machado@empresa.com.br",
    "senha":"#3c5x9cfg"
}

###
GET http://localhost:4000/agendamento
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nywibm9tZSI6Ildlc2xleSBNYWNoYWRvIiwiZW1haWwiOiJ3ZXNsZXkubWFjaGFkb0BlbXByZXNhLmNvbS5iciIsInRlbGVmb25lIjoiKDM0KSA5ODQ0My0xMjQ3IiwiYmFyYmVpcm8iOmZhbHNlLCJpYXQiOjE3MzM5NjA2MzAsImV4cCI6MTczNTI1NjYzMH0.Ddj8UlfYh4Dht10LHXKg7Qf-2-GphF3aqBkiTyND3Vo

###
GET http://localhost:4000/profissionais